server:
  port: ${SERVER_PORT:8085} # :8085은 기본값으로, 변수가 없을 경우 사용됩니다.

spring:
  application:
    name: msa-order-service
  rabbitmq:
    host: '{cipher}AYA5ayh5RfozNJEKf6Jw7Nk/x0UqgeZKKCaXGoVKE52zF/iWMNneXNIIMUaQ1sHbCB49ECmKKUGYQqViv9sOCWtqZBoFSOhuRVI1VNmMrK48m+0G50/j8FZ+VBYnrAmvqluae7e2vo2g68Wulq/ySoy+cpIzgzmGQsXA5rquG9o6qrBqR5Gleij5CQtV8WE29MoQCozRmGf0HBthJT6FTVVePzXggY5E6zSh9aNgnd0PkDLEQBhe1sWpTMISVqlJBNA7NacRRk0HY0h0NWad151lg3TEFHBpFoF66WDMt5X4L/qS3BGLj2f/ZnJWnIXE3b6kbvXTB3dMiMiibTbfTU4OWsNVM+5xkH7TkLCtlpYwCd6aMKDbcimtfpiHBmN0luLynSHMLt2Oxb1OEv2fIZNf4WW3VRHkoGXzah3VDE+x6pvM0eCFSws8Q8lXorughrQqd4tNzzLlH8HNqWIcVaV5ZfSrL5wsPE/F7/dUV+vqA0V9JG2sXq5UuqwjOCseOG6uEntogbwS4g/IVH2ZiVYXHU/JqrB83pJUDOGKSFSIXw=='
    port: 5672
    username: '{cipher}AYANT4RdUCsbxpKV3U8whMTCzQiidXMyOPKdcUkE6hMgY35FBJBovxZrriT6fjEiIhwtn4GJ/gTRWA91TZ2Jmye9/VSn3qlZ8OxdbWvONpLCEjU/geN1erW3v5zeT8XEf0hIOOz5Pc07X5GH8YV+FilOO4tPkYN278G5FAQZGLSLSSd+NSe9RLFjklCmuNQbQzIjjuXd1uik+XnUyG0hDgUQiBl4GrVDiBTk8g4v9LR7HU9kzAqnH2pO39JptA2d3p+9uXZI2fpGLUd1jOAOk3tgQiWOW8xp1LxJF5xoFVRctQunRBU2VfsISkfA8g6CdqwGVOE7wmXXMjo+OoMh45rXly9CniIgejuNRuMvuHUZ8QBEuaKwyuD1jkJYAWH07PjfBsApExgakEP9tNKzYWMktHmYQBq+eoRGKiujlAyne8aQyg7rd7MkUPlcOlj84CdrWh7y4gufXPPSElbaLzIoNA2uXpmWMRGF1CTKDmF6pWuKP/eEoD6EpjnUfAtS+Q7nh0nowSVaoPYV2V2NhRpUoIVcEdrdtrZ508pIsyNwbw=='
    password: '{cipher}AYANT4RdUCsbxpKV3U8whMTCzQiidXMyOPKdcUkE6hMgY35FBJBovxZrriT6fjEiIhwtn4GJ/gTRWA91TZ2Jmye9/VSn3qlZ8OxdbWvONpLCEjU/geN1erW3v5zeT8XEf0hIOOz5Pc07X5GH8YV+FilOO4tPkYN278G5FAQZGLSLSSd+NSe9RLFjklCmuNQbQzIjjuXd1uik+XnUyG0hDgUQiBl4GrVDiBTk8g4v9LR7HU9kzAqnH2pO39JptA2d3p+9uXZI2fpGLUd1jOAOk3tgQiWOW8xp1LxJF5xoFVRctQunRBU2VfsISkfA8g6CdqwGVOE7wmXXMjo+OoMh45rXly9CniIgejuNRuMvuHUZ8QBEuaKwyuD1jkJYAWH07PjfBsApExgakEP9tNKzYWMktHmYQBq+eoRGKiujlAyne8aQyg7rd7MkUPlcOlj84CdrWh7y4gufXPPSElbaLzIoNA2uXpmWMRGF1CTKDmF6pWuKP/eEoD6EpjnUfAtS+Q7nh0nowSVaoPYV2V2NhRpUoIVcEdrdtrZ508pIsyNwbw=='
  datasource:
    url: '{cipher}AYAFIfoY+8tVHy2VuM0vIo5miBOGD9XU+z/SI6KBwIXp6AiNbL+z5ua9hlU41Rw0Pd6nJtoLK/imJGZMpYj8SNT4Saq3N3rvdwMnM5aCKoc60UvrlB9k/pyCgQxING4/SaqBt3zGaDHF5INAvsPlsGfIc3N1Ff9oh8Z/4NK1jusIanYQsxqMDxtsZJ/u5aQU945voJ+cGdtuBsUQ093M4JmOe/LomODeG6CA+wzcivb5bUvZJqDRR3PJzq2V+FnDV8urCCijCRORCaboNbZ34aGsqDrBuB2FQj9GkBkmchZRFpvOVuo9Z1U1zt6XPbyiDplukPgC/YhgbZnCxw6NCtfjIWp/PqZGcKTbn0pE/bHl8EemID6svBxs3l3z3O4mTD2QppIy4zWe0orMQP0gHqtH37DgaAXcE0ttztFNZh0Qv7x9mon5AmT2js4w+IYfzstspZtzKdvgyVE9tD444c44NhBUyVeRo4ReIpK45wErCKZubrczv5Wsl3A4DWoCLgOBYLpqis4kDsrSxffa9z8VfVqrsRzOqjHiqOe5nx0Xv60mhbZ1CiiYruvYodmKKR1JLXzGZYiQsSOXKiJp8IOx'
    username: '{cipher}AYB9X66CKAky+BV3IMTn3i6oPCw9S+FfoD9wY83G8enMoxgq/Ei/4kwiLvlYs9o14CGHDTabSNUrUTrKXTUr8kUIaTa2vKub8p7VT3UiEo4KOuKEgBdwD1oB0cLiwrllyNP81iegjELZX452U+k0okgtQjGjI3qmAKEE8THVSUJUqCwFqdn+FpnKV7DrUhHdb4XCpnzWDMB24cwqQdBM9KMw+neCBdz27Z+iCcQdJvbfNBUqsvvdzBVS/sstUFoHR7xSVCrZS9qVrYZiVxL6rtLpQrRRM2JEha6hPdRJfy3AcwfSNyOtU+P/oMTfT/cJTBicO4p60kFNYRZ6xEGjYzueHLvkJwDzECye0eXEwjCm3qBaTNDiEe3pQ8o3Q88bL3bNBuhI1KkPtZ8zwiYMsEKtuane1+62+KDm0KkSWb+9SOfOEmiOBV3zicfysQpSuPfkt7BeWLtTNzsaqw+oj/faC87NKcqJtLXlXgmlyqwxSn0YL9JUkyVRBDhsyqJOWStfuT75kiHcmaQ+uDTLv6FQRb6Ob1UUYHvdQIPicB6XfQ=='
    password: '{cipher}AYB9X66CKAky+BV3IMTn3i6oPCw9S+FfoD9wY83G8enMoxgq/Ei/4kwiLvlYs9o14CGHDTabSNUrUTrKXTUr8kUIaTa2vKub8p7VT3UiEo4KOuKEgBdwD1oB0cLiwrllyNP81iegjELZX452U+k0okgtQjGjI3qmAKEE8THVSUJUqCwFqdn+FpnKV7DrUhHdb4XCpnzWDMB24cwqQdBM9KMw+neCBdz27Z+iCcQdJvbfNBUqsvvdzBVS/sstUFoHR7xSVCrZS9qVrYZiVxL6rtLpQrRRM2JEha6hPdRJfy3AcwfSNyOtU+P/oMTfT/cJTBicO4p60kFNYRZ6xEGjYzueHLvkJwDzECye0eXEwjCm3qBaTNDiEe3pQ8o3Q88bL3bNBuhI1KkPtZ8zwiYMsEKtuane1+62+KDm0KkSWb+9SOfOEmiOBV3zicfysQpSuPfkt7BeWLtTNzsaqw+oj/faC87NKcqJtLXlXgmlyqwxSn0YL9JUkyVRBDhsyqJOWStfuT75kiHcmaQ+uDTLv6FQRb6Ob1UUYHvdQIPicB6XfQ=='
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
  kafka:
    producer:
      bootstrap-servers: '{cipher}AYB5kdD2BZGmU2aHCcn9kGK/uMcwtwprKU0VSLtVBsu5sLhhvcHemELLpecJ4OvWgqZ3k0RRA5RMlr8VXAWaJZKWCo0yA9srsz5MzjBY8gaJP3yxO00gOPHDjSY8Wo6arqjVgz8QjwUV+rwketByN/HjJijNfnxMu0odYtXDSUTU6aXlOpVTM6mJka6gpQv8bNNWqHTQhiVA25e5lPS9wV7voKBXhZyfCBjPqVwQ7pTS0o+mnL9/ixgYrVbXPhfVFFqytYIyHExk61GsrHEdxU67BNs6O0WDmIIWhO2ALms9q1YJ6giUbKxRR0SGMbVUkkUyVmYGqeMac6gMooZrKwLwfpZecjsjgz60NsagYtHFuMTX26R0s40XSYqt2KHNahJJ+L73LmM/giOPlB/oXGxdfNMLwzVS1nQOnHsRqubm75OUwJaPhLiOle3rgza4XStuFq69GH6DizjcVMyb3rdxBYeFQoPSdAitrOcCpE3zryfkUeJKO9une21AD12cW0FYLb9ImEZQ4rnrNE3x8ym0ROwShruZZ4cIcOVxwbSLCQ=='
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: '{cipher}AYByt/ylUlnrGyWhiqeNJAwTSEX5jc3NlFfxM2akZ3TBOviTt8V29xQA8U8RT2oeZPCMC1r3xLhCBZgkRnMMD9gFkHJTX4v84muE5uz5rlO0A0wGIuUZxgSk2JAts9wr7SWzg8vC4drRv5cAQE8nIkghT+gcZcgIFuu3vYYZiqpLlJGMEPJll7JRGZGs4G2D2z7QHaI0i4M3+npw5lTxTbCX5mMmaw4Rd1dIDnEgU9H70evZ9gVS6vlETviLTB4tUe1KvI4VTUq0uqEqZb4RoRAx5MZYqvRzEYDJWdQgQJ8oJ1IIo3HcN0SWfIkyzkwvAflCz2gv1FJVfM5+gaifsyjgs+j5kA7wlefSITMNLSeuLVCjsMesATGL+2DNxtYjVnvArcZSKpC94A6dxPWVSlEyD3GkBp5EzHQL0NNynsTxoBR2A6H7e7hSld7ikvV4W82l/kpdSD9jCtnpvWLzGAQoxXMj7tzcMaZ5mqL2czZyEpHUMhGZQ1DCb5WJ+6RhE3iDiV9YMuTS9NmN5SQv0Jqu5Tn0ZB6yoYTKpN7Z6P+u41pyKWoT0EuHKiWwKJcBfEQ='
