spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa-user-1
    username: root
    password: '{cipher}AYBsfVZoLEsgDxeUbG8YnrGENsPQ444Vdp2+ARwuWpOtX4n2sp655ViFxexLJJlGzdgBEbRTnv0XUdOcjMDgETB28fc7yHt1ukTSH13/UINEDe8UExIk++siTO2hd0tiCxeIKbAemmMSziITUQ4wl3PfFWcc1cBcoAZQ7z8C81RZqNr72EduIBV/f+4VDVvNLwr2qmK6nn8l4aRbG2G9hb+4mis9JsX2SBoJWWVHc/ICv1FGL16ZbhmeZbe1ZmpeA08e0mA2VvOCcYi+UfF9go8aW9k5tWLc9hJq8HrEQvb2TqhyzzvprW0e/j1sKqKBZyLlgdfHdMsUDeMBDtBpq9K/bPQzv6FzkLS+DPwrQ3el3u7jaJoR8pURcBdamwQr8KMh98cyoZIEJj6iNy1t/n1uwGcp924raki/xb3rV4leaG83GPc6636qJcmY4OqRHbiXx/+gSkDFFtX65AGkTIakbK1r1d0dF0lF6UgcELzwMCOqcdcNqehIi1JMYtZP/X5IESnU+1I6+jnlmtUO+1pgsGVymuo6mzqe3GF3IWLxtw=='

order-service:
#  url: http://127.0.0.1:8001/order-service/%s/orders
  url: http://msa-order-service/order-service/%s/orders
  exception:
    order-is-empty: User's orders is empty.

token:
  expiration_time: 864000000
  secret: newest-my-very-long-secret-key-1234567890123456-from-remote-repo-ecommerce

gateway:
  ip: localhost_9
