spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}04cba31990a5e03bb7b305d577ef529a4d45f2b43fc20a85e397bb391ec02b17'

order-service:
  url: http://127.0.0.1:8001/order-service/%s/orders
#  url: http://order-service/order-service/%s/orders
  exception:
    order-is-empty: User's orders is empty.
